<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns="http://www.viasat.com/XMLSchema/v1/Fault"
	targetNamespace="http://www.viasat.com/XMLSchema/v1/Fault"
	elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:complexType name="ValidationError">
		<xs:sequence>
			<xs:element name="validationCode" type="xs:string">
				<xs:annotation>
					<xs:documentation>The reason that the validation error occurred
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="input" type="Input" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Information about the input field that this error
						applies to.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Input">
		<xs:sequence>
			<xs:element name="field" type="xs:string">
				<xs:annotation>
					<xs:documentation>The field that the validation error applies to
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="value" type="xs:string">
				<xs:annotation>
					<xs:documentation>The value that was supplied for this field.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="FaultDetail">
		<xs:sequence>
			<xs:element name="node" type="xs:string">
				<xs:annotation>
					<xs:documentation>URI of the node that generated the problem.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="timestamp" type="xs:dateTime">
				<xs:annotation>
					<xs:documentation>Time the error occurred.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="trackingKey" type="xs:string">
				<xs:annotation>
					<xs:documentation>Tracking key to aid log file search.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="method" type="xs:string">
				<xs:annotation>
					<xs:documentation>Class name and method where the validation
						exception was generated</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="contextPath" type="xs:string">
				<xs:annotation>
					<xs:documentation>Context path of the webservice that threw this exception</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="message" type ="xs:string" minOccurs = "0" maxOccurs ="1"/>
			<xs:element name="validationError" type="ValidationError" minOccurs = "0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>The validation error that occurred
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="faultDetail" type="FaultDetail" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>If this validation exception was generated by
						another webservice, the validation exception</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>	
	<xs:element name="faultDetail" type="FaultDetail" />
</xs:schema>
